# Generated by Django 2.2.1 on 2019-05-25 06:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=20, unique=True)),
                ('User_Password', models.CharField(max_length=20)),
                ('User_Nickname', models.CharField(max_length=20, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.CharField(max_length=40)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
            options={
                'unique_together': {('File_Name', 'Owner')},
            },
        ),
    ]
