# Generated by Django 2.0.13 on 2019-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190530_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_Password',
            field=models.CharField(max_length=256),
        ),
    ]
