# Generated by Django 2.0.13 on 2019-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190606_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='File_Name',
            field=models.CharField(max_length=256),
        ),
    ]
